name: cd-firebase-android
on:
  push:
    branches: [develop, release, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Permisos
      run: chmod +x gradlew
    - name: build release 
      run: ./gradlew build
    - name: build release 
      run: ./gradlew assembleRelease
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: 1:27123300702:android:db5e242e44a409d00f37cf
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk


