name: noti
on:
  push:
    branches: [main]
jobs:
  Noti:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: jeremyjor299@gmail.com
          from: Me

