name: noti
on:
  push:
    branches: [main]
jobs:
  Noti:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.coma
          server_port: 587
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: jeremyjor299@gmail.com
          from: Luke Skywalker 
          convert_markdown: true
          priority: low